//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegacyApp.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatedPerson
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string ZodiacSign { get; set; }
        public long UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
