//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegacyApp.Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersSetting
    {
        public long Id { get; set; }
        public bool IsVisible { get; set; }
        public string Theme { get; set; }
        public string ProfileType { get; set; }
    
        public virtual User User { get; set; }
    }
}
